/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.projetos.jframes;

import backend.controllers.AplicacaoController;
import backend.dto.ProjetoDTO;
import database.dao.ProjetoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author joao
 */
public class ListaProjetos extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel;
    private List<ProjetoDTO> projetos;
    
    public ListaProjetos() {
        initComponents();
        inicializarComponentes();
    }

    
    public void inicializarComponentes()
    {
        // tabela
        defaultTableModel = (DefaultTableModel) tabelaProjetos.getModel();
        
        projetos
                = ProjetoDAO
                        .getByIdUsuario(
                                AplicacaoController
                                        .getIdUsuarioSelecionado()
                        );
        
        if(!projetos.isEmpty())
        {
            for(ProjetoDTO projeto : projetos)
            {
                defaultTableModel.addRow(new Object[]{projeto.getNome()});
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTabelaProjetos = new javax.swing.JLabel();
        scrollPaneTabelaProjetos = new javax.swing.JScrollPane();
        tabelaProjetos = new javax.swing.JTable();
        textFieldPesquisar = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        botaoPesquisar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1295, 697));

        tituloTabelaProjetos.setText("Projetos");

        tabelaProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));
        tabelaProjetos.setRowHeight(40);
        scrollPaneTabelaProjetos.setViewportView(tabelaProjetos);

        textFieldPesquisar.setPreferredSize(new java.awt.Dimension(443, 40));

        botaoPesquisar.setText("Selecionar");
        botaoPesquisar.setPreferredSize(new java.awt.Dimension(137, 40));
        botaoPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPesquisarMouseClicked(evt);
            }
        });
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoPesquisar1.setText("Pesquisar");
        botaoPesquisar1.setPreferredSize(new java.awt.Dimension(137, 40));
        botaoPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTabelaProjetos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPaneTabelaProjetos)
                            .addComponent(textFieldPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(tituloTabelaProjetos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabelaProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisar1ActionPerformed

    private void botaoPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPesquisarMouseClicked
        int i = tabelaProjetos.getSelectedRow();
        
        if(projetos.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Não há projeto");
            return;
        }
        
        if(projetos.get(i) != null)
        {
            
            int idProjeto 
                    = projetos
                            .get(i)
                            .getIdProjeto();
            
            AplicacaoController
                    .setIdProjetoSelecionado(idProjeto);
            
            JOptionPane.showMessageDialog(null, "Selecionado");
        } else {
            JOptionPane.showMessageDialog(null, "Não há projeto");
        }
        
    }//GEN-LAST:event_botaoPesquisarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoPesquisar1;
    private javax.swing.JScrollPane scrollPaneTabelaProjetos;
    private javax.swing.JTable tabelaProjetos;
    private javax.swing.JTextField textFieldPesquisar;
    private javax.swing.JLabel tituloTabelaProjetos;
    // End of variables declaration//GEN-END:variables
}
