/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.projetos.jframes;

import backend.controllers.AplicacaoController;
import backend.dto.ProjetoDTO;
import database.dao.ProjetoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author joao
 */
public class RemoverProjeto extends javax.swing.JFrame {

    /**
     * Creates new form Remover
     */
    public RemoverProjeto() {
        initComponents();
        inicializarComponentes();
    }

    
    public void inicializarComponentes()
    {
        // erros
        erroRemover.setVisible(false);
        
        // fields
        ProjetoDTO projeto
                = ProjetoDAO
                        .getByIdProjeto(
                                AplicacaoController
                                        .getIdProjetoSelecionado()
                        );
        
        if(projeto != null)
        {
            textFieldNome.setText(projeto.getNome());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Não há projeto");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNome = new javax.swing.JPanel();
        tituloNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        botaoRemover = new javax.swing.JButton();
        erroRemover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1295, 697));

        tituloNome.setText("Nome");

        textFieldNome.setEditable(false);
        textFieldNome.setText("Não Selecionado");
        textFieldNome.setToolTipText("");
        textFieldNome.setEnabled(false);
        textFieldNome.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputNomeLayout = new javax.swing.GroupLayout(inputNome);
        inputNome.setLayout(inputNomeLayout);
        inputNomeLayout.setHorizontalGroup(
            inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        inputNomeLayout.setVerticalGroup(
            inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botaoRemover.setForeground(new java.awt.Color(242, 43, 43));
        botaoRemover.setText("Excluir");
        botaoRemover.setMaximumSize(new java.awt.Dimension(127, 40));
        botaoRemover.setMinimumSize(new java.awt.Dimension(127, 40));
        botaoRemover.setPreferredSize(new java.awt.Dimension(127, 40));
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        erroRemover.setForeground(new java.awt.Color(242, 13, 13));
        erroRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroRemover.setText("erro!");
        erroRemover.setPreferredSize(new java.awt.Dimension(453, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(583, 583, 583))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(erroRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(420, 420, 420))))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(erroRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        
        ProjetoDTO projeto
                = ProjetoDAO
                        .getByIdProjeto(
                                AplicacaoController
                                        .getIdProjetoSelecionado()
                        );
        
        if(projeto != null)
        {
            ProjetoDAO
                    .removeById(
                            AplicacaoController
                                    .getIdProjetoSelecionado()
                    );
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Não há projeto para excluir");
        }
        
    }//GEN-LAST:event_botaoRemoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRemover;
    private javax.swing.JLabel erroRemover;
    private javax.swing.JPanel inputNome;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JLabel tituloNome;
    // End of variables declaration//GEN-END:variables
}
