/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.usuario.jframes;

import database.dao.UsuarioDAO;
import backend.controllers.AplicacaoController;
import backend.dto.UsuarioDTO;
import backend.utils.validacao.login.ValidadorCadastrarUsuario;
import backend.utils.validacao.usuarios.ValidadorEditarUsuario;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author joao
 */
public class EditarUsuario extends javax.swing.JFrame {

    private boolean trocarSenha = false;
    
    /**
     * Creates new form Editar
     */
    public EditarUsuario() {
        initComponents();
        inicializarComponentes();
    }

    private void inicializarComponentes () {
        
        // mensagens de erro
        mensagensDeErro = new ArrayList<>();
                
        mensagensDeErro.addAll(
                
                Arrays.asList(
                        erroNomeCompleto,
                        erroNomeDeUsuario,
                        erroEmail,
                        erroSenha,
                        erroNovaSenha,
                        erroConfirmarSenha,
                        erroTelefone
                )
                
        );
        
        mensagensDeErro.forEach( 
                erro -> {
                    erro.setVisible(false);
                }
        );
        
        // textFields
        
        int idUsuario 
                = AplicacaoController
                        .getIdUsuarioSelecionado();
        
        UsuarioDTO usuario 
                = UsuarioDAO
                        .getById(
                              idUsuario  
                        );
        
        textFieldNomeCompleto.setText(usuario.getNomeCompleto());
        textFieldNomeUsuario.setText(usuario.getNomeUsuario());
        textFieldEmail.setText(usuario.getEmail());
        textFieldTelefone.setText(usuario.getTelefone());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        erroEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        tituloEmail = new javax.swing.JLabel();
        erroSenha = new javax.swing.JLabel();
        tituloSenha = new javax.swing.JLabel();
        tituloNovaSenha = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        erroTelefone = new javax.swing.JLabel();
        tituloTelefone = new javax.swing.JLabel();
        textFieldNomeCompleto = new javax.swing.JTextField();
        tituloNomeCompleto = new javax.swing.JLabel();
        erroNomeCompleto = new javax.swing.JLabel();
        textFieldNomeUsuario = new javax.swing.JTextField();
        tituloNomeDeUsuario = new javax.swing.JLabel();
        erroNomeDeUsuario = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        passwordFieldNovaSenha = new javax.swing.JPasswordField();
        passwordFieldSenha = new javax.swing.JPasswordField();
        passwordFieldConfirmarSenha = new javax.swing.JPasswordField();
        tituloConfirmarSenha = new javax.swing.JLabel();
        erroConfirmarSenha = new javax.swing.JLabel();
        erroNovaSenha = new javax.swing.JLabel();
        botaoTrocarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1295, 697));

        layeredPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        layeredPane.setViewportView(null);

        panel.setPreferredSize(new java.awt.Dimension(1295, 800));
        panel.setRequestFocusEnabled(false);

        erroEmail.setForeground(new java.awt.Color(242, 13, 13));
        erroEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroEmail.setText("erro!");
        erroEmail.setPreferredSize(new java.awt.Dimension(453, 18));

        textFieldEmail.setToolTipText("");
        textFieldEmail.setPreferredSize(new java.awt.Dimension(453, 35));
        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        tituloEmail.setText("E-mail");

        erroSenha.setForeground(new java.awt.Color(242, 13, 13));
        erroSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroSenha.setText("erro!");
        erroSenha.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloSenha.setText("Senha");

        tituloNovaSenha.setText("Nova Senha");

        textFieldTelefone.setToolTipText("");
        textFieldTelefone.setPreferredSize(new java.awt.Dimension(453, 35));
        textFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefoneActionPerformed(evt);
            }
        });

        erroTelefone.setForeground(new java.awt.Color(242, 13, 13));
        erroTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroTelefone.setText("erro!");
        erroTelefone.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloTelefone.setText("Telefone");

        textFieldNomeCompleto.setToolTipText("");
        textFieldNomeCompleto.setPreferredSize(new java.awt.Dimension(453, 35));
        textFieldNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeCompletoActionPerformed(evt);
            }
        });

        tituloNomeCompleto.setText("Nome Completo");

        erroNomeCompleto.setForeground(new java.awt.Color(242, 13, 13));
        erroNomeCompleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroNomeCompleto.setText("erro!");
        erroNomeCompleto.setPreferredSize(new java.awt.Dimension(453, 18));

        textFieldNomeUsuario.setToolTipText("");
        textFieldNomeUsuario.setPreferredSize(new java.awt.Dimension(453, 35));
        textFieldNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeUsuarioActionPerformed(evt);
            }
        });

        tituloNomeDeUsuario.setText("Nome de Usuário");

        erroNomeDeUsuario.setForeground(new java.awt.Color(242, 13, 13));
        erroNomeDeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroNomeDeUsuario.setText("erro!");
        erroNomeDeUsuario.setPreferredSize(new java.awt.Dimension(453, 18));

        botaoSalvar.setText("Salvar");
        botaoSalvar.setMaximumSize(new java.awt.Dimension(127, 40));
        botaoSalvar.setMinimumSize(new java.awt.Dimension(127, 40));
        botaoSalvar.setPreferredSize(new java.awt.Dimension(127, 40));
        botaoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSalvarMouseClicked(evt);
            }
        });
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        passwordFieldNovaSenha.setEnabled(false);
        passwordFieldNovaSenha.setPreferredSize(new java.awt.Dimension(453, 35));
        passwordFieldNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldNovaSenhaActionPerformed(evt);
            }
        });

        passwordFieldSenha.setEnabled(false);
        passwordFieldSenha.setPreferredSize(new java.awt.Dimension(453, 35));
        passwordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldSenhaActionPerformed(evt);
            }
        });

        passwordFieldConfirmarSenha.setEnabled(false);
        passwordFieldConfirmarSenha.setPreferredSize(new java.awt.Dimension(453, 35));
        passwordFieldConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldConfirmarSenhaActionPerformed(evt);
            }
        });

        tituloConfirmarSenha.setText("Confirmar Senha");

        erroConfirmarSenha.setForeground(new java.awt.Color(242, 13, 13));
        erroConfirmarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroConfirmarSenha.setText("erro!");
        erroConfirmarSenha.setPreferredSize(new java.awt.Dimension(453, 18));

        erroNovaSenha.setForeground(new java.awt.Color(242, 13, 13));
        erroNovaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroNovaSenha.setText("erro!");
        erroNovaSenha.setPreferredSize(new java.awt.Dimension(453, 18));

        botaoTrocarSenha.setText("Trocar Senha");
        botaoTrocarSenha.setMaximumSize(new java.awt.Dimension(127, 40));
        botaoTrocarSenha.setMinimumSize(new java.awt.Dimension(127, 40));
        botaoTrocarSenha.setPreferredSize(new java.awt.Dimension(127, 40));
        botaoTrocarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTrocarSenhaMouseClicked(evt);
            }
        });
        botaoTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTrocarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(erroNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tituloNomeDeUsuario)
                                    .addComponent(textFieldNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(erroNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldNomeCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tituloNomeCompleto)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(erroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tituloTelefone)
                                    .addComponent(textFieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(erroConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordFieldConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloConfirmarSenha)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(erroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addComponent(tituloSenha)
                                    .addGap(410, 410, 410)))
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(erroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tituloEmail)
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(passwordFieldNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloNovaSenha)
                            .addComponent(erroNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(botaoTrocarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(477, 477, 477))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tituloNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tituloNomeDeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tituloEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tituloSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tituloNovaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFieldNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tituloConfirmarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFieldConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tituloTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoTrocarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPane.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void textFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelefoneActionPerformed

    private void textFieldNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeCompletoActionPerformed

    private void textFieldNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeUsuarioActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void passwordFieldNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldNovaSenhaActionPerformed

    private void passwordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldSenhaActionPerformed

    private void passwordFieldConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldConfirmarSenhaActionPerformed

    private void botaoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvarMouseClicked
        boolean usuarioValido 
                = ValidadorEditarUsuario
                        .eValido(
                textFieldNomeCompleto.getText(), 
                textFieldNomeUsuario.getText(),
                textFieldEmail.getText(),
                passwordFieldSenha.getText(),
                passwordFieldNovaSenha.getText(), 
                passwordFieldConfirmarSenha.getText(), 
                textFieldTelefone.getText(),
                trocarSenha
                        );
        
        if(usuarioValido)
        {
            
            
            String senhaUsuario;
            if(!trocarSenha)
            {
                senhaUsuario
                        = UsuarioDAO.getById(
                                AplicacaoController
                                        .getIdUsuarioSelecionado()
                        ).getSenha();  
            }
            else {
                senhaUsuario = passwordFieldNovaSenha.getText();
            }
            UsuarioDTO usuario = new UsuarioDTO(
                textFieldNomeCompleto.getText(), 
                textFieldNomeUsuario.getText(),
                textFieldEmail.getText(),
                senhaUsuario, 
                textFieldTelefone.getText()
            );
            
            usuario.setIdUsuario(
                    AplicacaoController
                            .getIdUsuarioSelecionado()
            );
            
            
            UsuarioDAO.updateById(usuario);
            
            resetarFields();
            
        }
    }//GEN-LAST:event_botaoSalvarMouseClicked

    private void botaoTrocarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTrocarSenhaMouseClicked
        if(trocarSenha == false)
        {
            passwordFieldSenha.setEnabled(true);
            passwordFieldNovaSenha.setEnabled(true);
            passwordFieldConfirmarSenha.setEnabled(true);
            trocarSenha = true;
        }
    }//GEN-LAST:event_botaoTrocarSenhaMouseClicked

    private void botaoTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTrocarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTrocarSenhaActionPerformed

    private void resetarFields()
    {
        // senhas
        passwordFieldSenha.setText("");
        passwordFieldNovaSenha.setText("");
        passwordFieldConfirmarSenha.setText("");
        
        passwordFieldSenha.setEnabled(false);
        passwordFieldNovaSenha.setEnabled(false);
        passwordFieldConfirmarSenha.setEnabled(false);
        trocarSenha = false;
    }
    
    private List<JLabel> mensagensDeErro;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoTrocarSenha;
    private javax.swing.JLabel erroConfirmarSenha;
    private javax.swing.JLabel erroEmail;
    private javax.swing.JLabel erroNomeCompleto;
    private javax.swing.JLabel erroNomeDeUsuario;
    private javax.swing.JLabel erroNovaSenha;
    private javax.swing.JLabel erroSenha;
    private javax.swing.JLabel erroTelefone;
    private javax.swing.JScrollPane layeredPane;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField passwordFieldConfirmarSenha;
    private javax.swing.JPasswordField passwordFieldNovaSenha;
    private javax.swing.JPasswordField passwordFieldSenha;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNomeCompleto;
    private javax.swing.JTextField textFieldNomeUsuario;
    private javax.swing.JTextField textFieldTelefone;
    private javax.swing.JLabel tituloConfirmarSenha;
    private javax.swing.JLabel tituloEmail;
    private javax.swing.JLabel tituloNomeCompleto;
    private javax.swing.JLabel tituloNomeDeUsuario;
    private javax.swing.JLabel tituloNovaSenha;
    private javax.swing.JLabel tituloSenha;
    private javax.swing.JLabel tituloTelefone;
    // End of variables declaration//GEN-END:variables
}
