/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.resources.jframes;

/**
 *
 * @author joao
 */
public class Conteudo extends javax.swing.JFrame {

    /**
     * Creates new form Conteudos
     */
    public Conteudo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoUsL = new javax.swing.JScrollPane();
        panelCoUsL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabCo = new javax.swing.JLayeredPane();
        CoUsAu = new javax.swing.JScrollPane();
        panelCoUsAu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CoUsEu = new javax.swing.JScrollPane();
        panelCoUsEu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CoPrL = new javax.swing.JScrollPane();
        panelCoPrL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CoPrAp = new javax.swing.JScrollPane();
        panelCoPrAp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CoPrEp = new javax.swing.JScrollPane();
        panelCoPrEp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CoReqL = new javax.swing.JScrollPane();
        panelCoReqL = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CoReqAr = new javax.swing.JScrollPane();
        panelCoReqAr = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CoReqEr = new javax.swing.JScrollPane();
        panelCoReqEr = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CoRelPr = new javax.swing.JScrollPane();
        panelCoRelPr = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CoRelReq = new javax.swing.JScrollPane();
        panelCoRelReq = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CoUsL1 = new javax.swing.JScrollPane();
        panelCoUsL1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        CoUsL.setBorder(null);
        CoUsL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        CoUsL.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoUsL.setBorder(null);
        panelCoUsL.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel1.setText("panelCoUsL");

        javax.swing.GroupLayout panelCoUsLLayout = new javax.swing.GroupLayout(panelCoUsL);
        panelCoUsL.setLayout(panelCoUsLLayout);
        panelCoUsLLayout.setHorizontalGroup(
            panelCoUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsLLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel1)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        panelCoUsLLayout.setVerticalGroup(
            panelCoUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsLLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsL.setViewportView(panelCoUsL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(918, 810));
        setResizable(false);

        tabCo.setPreferredSize(new java.awt.Dimension(918, 810));

        CoUsAu.setBorder(null);
        CoUsAu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoUsAu.setPreferredSize(new java.awt.Dimension(918, 810));
        CoUsAu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoUsAuMouseClicked(evt);
            }
        });

        panelCoUsAu.setBorder(null);
        panelCoUsAu.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel2.setText("panelCoUsAu");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCoUsAuLayout = new javax.swing.GroupLayout(panelCoUsAu);
        panelCoUsAu.setLayout(panelCoUsAuLayout);
        panelCoUsAuLayout.setHorizontalGroup(
            panelCoUsAuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsAuLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel2)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        panelCoUsAuLayout.setVerticalGroup(
            panelCoUsAuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsAuLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsAu.setViewportView(panelCoUsAu);

        CoUsEu.setBorder(null);
        CoUsEu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoUsEu.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoUsEu.setBorder(null);
        panelCoUsEu.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel3.setText("panelCoUsEu");

        javax.swing.GroupLayout panelCoUsEuLayout = new javax.swing.GroupLayout(panelCoUsEu);
        panelCoUsEu.setLayout(panelCoUsEuLayout);
        panelCoUsEuLayout.setHorizontalGroup(
            panelCoUsEuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsEuLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel3)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        panelCoUsEuLayout.setVerticalGroup(
            panelCoUsEuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsEuLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel3)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsEu.setViewportView(panelCoUsEu);

        CoPrL.setBorder(null);
        CoPrL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoPrL.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoPrL.setBorder(null);
        panelCoPrL.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel4.setText("panelCoPrL");

        javax.swing.GroupLayout panelCoPrLLayout = new javax.swing.GroupLayout(panelCoPrL);
        panelCoPrL.setLayout(panelCoPrLLayout);
        panelCoPrLLayout.setHorizontalGroup(
            panelCoPrLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrLLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel4)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        panelCoPrLLayout.setVerticalGroup(
            panelCoPrLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrLLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel4)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoPrL.setViewportView(panelCoPrL);

        CoPrAp.setBorder(null);
        CoPrAp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoPrAp.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoPrAp.setBorder(null);
        panelCoPrAp.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel5.setText("panelCoPrAp");

        javax.swing.GroupLayout panelCoPrApLayout = new javax.swing.GroupLayout(panelCoPrAp);
        panelCoPrAp.setLayout(panelCoPrApLayout);
        panelCoPrApLayout.setHorizontalGroup(
            panelCoPrApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrApLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel5)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        panelCoPrApLayout.setVerticalGroup(
            panelCoPrApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrApLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel5)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoPrAp.setViewportView(panelCoPrAp);

        CoPrEp.setBorder(null);
        CoPrEp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoPrEp.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoPrEp.setBorder(null);
        panelCoPrEp.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel6.setText("panelCoPrEp");

        javax.swing.GroupLayout panelCoPrEpLayout = new javax.swing.GroupLayout(panelCoPrEp);
        panelCoPrEp.setLayout(panelCoPrEpLayout);
        panelCoPrEpLayout.setHorizontalGroup(
            panelCoPrEpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrEpLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel6)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        panelCoPrEpLayout.setVerticalGroup(
            panelCoPrEpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrEpLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel6)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoPrEp.setViewportView(panelCoPrEp);

        CoReqL.setBorder(null);
        CoReqL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoReqL.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoReqL.setBorder(null);
        panelCoReqL.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel8.setText("panelCoReqL");

        javax.swing.GroupLayout panelCoReqLLayout = new javax.swing.GroupLayout(panelCoReqL);
        panelCoReqL.setLayout(panelCoReqLLayout);
        panelCoReqLLayout.setHorizontalGroup(
            panelCoReqLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqLLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel8)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        panelCoReqLLayout.setVerticalGroup(
            panelCoReqLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqLLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel8)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoReqL.setViewportView(panelCoReqL);

        CoReqAr.setBorder(null);
        CoReqAr.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoReqAr.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoReqAr.setBorder(null);
        panelCoReqAr.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel7.setText("panelCoReqAr");

        javax.swing.GroupLayout panelCoReqArLayout = new javax.swing.GroupLayout(panelCoReqAr);
        panelCoReqAr.setLayout(panelCoReqArLayout);
        panelCoReqArLayout.setHorizontalGroup(
            panelCoReqArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqArLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel7)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        panelCoReqArLayout.setVerticalGroup(
            panelCoReqArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqArLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel7)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoReqAr.setViewportView(panelCoReqAr);

        CoReqEr.setBorder(null);
        CoReqEr.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoReqEr.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoReqEr.setBorder(null);
        panelCoReqEr.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel9.setText("panelCoReqEr");

        javax.swing.GroupLayout panelCoReqErLayout = new javax.swing.GroupLayout(panelCoReqEr);
        panelCoReqEr.setLayout(panelCoReqErLayout);
        panelCoReqErLayout.setHorizontalGroup(
            panelCoReqErLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqErLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel9)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        panelCoReqErLayout.setVerticalGroup(
            panelCoReqErLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqErLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel9)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoReqEr.setViewportView(panelCoReqEr);

        CoRelPr.setBorder(null);
        CoRelPr.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoRelPr.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoRelPr.setBorder(null);
        panelCoRelPr.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel10.setText("panelCoRelPr");

        javax.swing.GroupLayout panelCoRelPrLayout = new javax.swing.GroupLayout(panelCoRelPr);
        panelCoRelPr.setLayout(panelCoRelPrLayout);
        panelCoRelPrLayout.setHorizontalGroup(
            panelCoRelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelPrLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel10)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        panelCoRelPrLayout.setVerticalGroup(
            panelCoRelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelPrLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel10)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoRelPr.setViewportView(panelCoRelPr);

        CoRelReq.setBorder(null);
        CoRelReq.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoRelReq.setPreferredSize(new java.awt.Dimension(918, 810));

        panelCoRelReq.setBorder(null);
        panelCoRelReq.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel11.setText("panelCoRelReq");

        javax.swing.GroupLayout panelCoRelReqLayout = new javax.swing.GroupLayout(panelCoRelReq);
        panelCoRelReq.setLayout(panelCoRelReqLayout);
        panelCoRelReqLayout.setHorizontalGroup(
            panelCoRelReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelReqLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel11)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        panelCoRelReqLayout.setVerticalGroup(
            panelCoRelReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelReqLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel11)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoRelReq.setViewportView(panelCoRelReq);

        CoUsL1.setBorder(null);
        CoUsL1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoUsL1.setPreferredSize(new java.awt.Dimension(918, 810));
        CoUsL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoUsL1MouseClicked(evt);
            }
        });

        panelCoUsL1.setBorder(null);
        panelCoUsL1.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel12.setText("panelCoUsAu");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCoUsL1Layout = new javax.swing.GroupLayout(panelCoUsL1);
        panelCoUsL1.setLayout(panelCoUsL1Layout);
        panelCoUsL1Layout.setHorizontalGroup(
            panelCoUsL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsL1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel12)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        panelCoUsL1Layout.setVerticalGroup(
            panelCoUsL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsL1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel12)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsL1.setViewportView(panelCoUsL1);

        tabCo.setLayer(CoUsAu, 14);
        tabCo.setLayer(CoUsEu, 13);
        tabCo.setLayer(CoPrL, 12);
        tabCo.setLayer(CoPrAp, 11);
        tabCo.setLayer(CoPrEp, 10);
        tabCo.setLayer(CoReqL, 9);
        tabCo.setLayer(CoReqAr, 8);
        tabCo.setLayer(CoReqEr, 7);
        tabCo.setLayer(CoRelPr, 6);
        tabCo.setLayer(CoRelReq, 5);
        tabCo.setLayer(CoUsL1, 15);

        javax.swing.GroupLayout tabCoLayout = new javax.swing.GroupLayout(tabCo);
        tabCo.setLayout(tabCoLayout);
        tabCoLayout.setHorizontalGroup(
            tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoUsAu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoUsEu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqEr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CoUsL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        tabCoLayout.setVerticalGroup(
            tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCoLayout.createSequentialGroup()
                .addComponent(CoUsAu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoUsEu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CoPrL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CoPrAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CoPrEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CoReqAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CoReqL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CoReqEr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CoUsL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tabCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tabCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoUsAuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoUsAuMouseClicked

    }//GEN-LAST:event_CoUsAuMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        CoUsAu.setVisible(false);
        System.out.println("1");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void CoUsL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoUsL1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CoUsL1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conteudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CoPrAp;
    private javax.swing.JScrollPane CoPrEp;
    private javax.swing.JScrollPane CoPrL;
    private javax.swing.JScrollPane CoRelPr;
    private javax.swing.JScrollPane CoRelReq;
    private javax.swing.JScrollPane CoReqAr;
    private javax.swing.JScrollPane CoReqEr;
    private javax.swing.JScrollPane CoReqL;
    private javax.swing.JScrollPane CoUsAu;
    private javax.swing.JScrollPane CoUsEu;
    private javax.swing.JScrollPane CoUsL;
    private javax.swing.JScrollPane CoUsL1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelCoPrAp;
    private javax.swing.JPanel panelCoPrEp;
    private javax.swing.JPanel panelCoPrL;
    private javax.swing.JPanel panelCoRelPr;
    private javax.swing.JPanel panelCoRelReq;
    private javax.swing.JPanel panelCoReqAr;
    private javax.swing.JPanel panelCoReqEr;
    private javax.swing.JPanel panelCoReqL;
    private javax.swing.JPanel panelCoUsAu;
    private javax.swing.JPanel panelCoUsEu;
    private javax.swing.JPanel panelCoUsL;
    private javax.swing.JPanel panelCoUsL1;
    private javax.swing.JLayeredPane tabCo;
    // End of variables declaration//GEN-END:variables
}
