/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.resources.jframes;

/**
 *
 * @author joao
 */
public class TesteLayeredPanels extends javax.swing.JPanel {

    /**
     * Creates new form TesteLayeredPanels
     */
    public TesteLayeredPanels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabOp = new javax.swing.JPanel();
        titleOp = new javax.swing.JPanel();
        textoTitleOp = new javax.swing.JLabel();
        layeredOp = new javax.swing.JLayeredPane();
        panelOpUs = new javax.swing.JPanel();
        botaoOpUsEu = new javax.swing.JPanel();
        textoBotaoOpUsEu = new javax.swing.JLabel();
        iconeBotaoOpUsEu = new javax.swing.JLabel();
        botaoOpUsL = new javax.swing.JPanel();
        textoBotaoOpUsL = new javax.swing.JLabel();
        iconeBotaoOpUsL = new javax.swing.JLabel();
        botaoOpUsAu = new javax.swing.JPanel();
        textoBotaoOpUsAu = new javax.swing.JLabel();
        iconeBotaoOpUsAu = new javax.swing.JLabel();
        panelOpPr = new javax.swing.JPanel();
        botaoOpPrEp = new javax.swing.JPanel();
        textoBotaoOpPrEp = new javax.swing.JLabel();
        iconeBotaoOpPrEp = new javax.swing.JLabel();
        botaoOpPrL = new javax.swing.JPanel();
        textoBotaoOpPrL = new javax.swing.JLabel();
        iconeBotaoOpPrL = new javax.swing.JLabel();
        botaoOpPrAp = new javax.swing.JPanel();
        textoBotaoOpPrAp = new javax.swing.JLabel();
        iconeBotaoOpPrAp = new javax.swing.JLabel();
        panelOpReq = new javax.swing.JPanel();
        botaoOpReqEr = new javax.swing.JPanel();
        textoBotaoOpReqEr = new javax.swing.JLabel();
        iconeBotaoOpReqEr = new javax.swing.JLabel();
        botaoOpReqL = new javax.swing.JPanel();
        textoBotaoOpReqL = new javax.swing.JLabel();
        iconeBotaoOpReqL = new javax.swing.JLabel();
        botaoOpReqAr = new javax.swing.JPanel();
        textoBotaoOpReqAr = new javax.swing.JLabel();
        iconeBotaoOpReqAr = new javax.swing.JLabel();
        panelOpRel = new javax.swing.JPanel();
        botaoOpRelPr = new javax.swing.JPanel();
        textoBotaoOpRelPr = new javax.swing.JLabel();
        iconeBotaoOpRelPr = new javax.swing.JLabel();
        botaoOpRelReq = new javax.swing.JPanel();
        textoBotaoOpRelReq = new javax.swing.JLabel();
        iconeBotaoOpRelReq = new javax.swing.JLabel();
        tabCo = new javax.swing.JLayeredPane();
        CoUsL1 = new javax.swing.JPanel();
        CoUsL = new javax.swing.JScrollPane();
        panelCoUsL = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        CoRelReq1 = new javax.swing.JPanel();
        CoRelReq = new javax.swing.JScrollPane();
        panelCoRelReq = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CoRelPr1 = new javax.swing.JPanel();
        CoRelPr = new javax.swing.JScrollPane();
        panelCoRelPr = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CoReqEr1 = new javax.swing.JPanel();
        CoReqEr = new javax.swing.JScrollPane();
        panelCoReqEr = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CoReqAr1 = new javax.swing.JPanel();
        CoReqAr = new javax.swing.JScrollPane();
        panelCoReqAr = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CoReqL1 = new javax.swing.JPanel();
        CoReqL = new javax.swing.JScrollPane();
        panelCoReqL = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CoPrEp1 = new javax.swing.JPanel();
        CoPrEp = new javax.swing.JScrollPane();
        panelCoPrEp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CoPrAp1 = new javax.swing.JPanel();
        CoPrAp = new javax.swing.JScrollPane();
        panelCoPrAp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CoUsEu1 = new javax.swing.JPanel();
        CoUsEu = new javax.swing.JScrollPane();
        panelCoUsEu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CoPrL1 = new javax.swing.JPanel();
        CoPrL = new javax.swing.JScrollPane();
        panelCoPrL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CoUsAu1 = new javax.swing.JPanel();
        CoUsAu = new javax.swing.JScrollPane();
        panelCoUsAu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        tabOp.setBackground(new java.awt.Color(238, 238, 238));
        tabOp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 61, 16)));
        tabOp.setPreferredSize(new java.awt.Dimension(374, 810));

        titleOp.setBackground(new java.awt.Color(143, 140, 157));
        titleOp.setPreferredSize(new java.awt.Dimension(374, 40));

        textoTitleOp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        textoTitleOp.setText("Opções");

        javax.swing.GroupLayout titleOpLayout = new javax.swing.GroupLayout(titleOp);
        titleOp.setLayout(titleOpLayout);
        titleOpLayout.setHorizontalGroup(
            titleOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleOpLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(textoTitleOp)
                .addGap(160, 160, 160))
        );
        titleOpLayout.setVerticalGroup(
            titleOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleOpLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textoTitleOp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredOp.setPreferredSize(new java.awt.Dimension(374, 254));

        panelOpUs.setBackground(new java.awt.Color(238, 238, 238));
        panelOpUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOpUsMouseClicked(evt);
            }
        });

        botaoOpUsEu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpUsEu.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpUsEu.setRequestFocusEnabled(false);

        textoBotaoOpUsEu.setText("Editar Usuário");

        iconeBotaoOpUsEu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpUsEuLayout = new javax.swing.GroupLayout(botaoOpUsEu);
        botaoOpUsEu.setLayout(botaoOpUsEuLayout);
        botaoOpUsEuLayout.setHorizontalGroup(
            botaoOpUsEuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpUsEuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textoBotaoOpUsEu)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpUsEuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpUsEu)
                .addGap(61, 61, 61))
        );
        botaoOpUsEuLayout.setVerticalGroup(
            botaoOpUsEuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpUsEuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpUsEu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoBotaoOpUsEu)
                .addGap(260, 260, 260))
        );

        botaoOpUsL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpUsL.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpUsL.setRequestFocusEnabled(false);

        textoBotaoOpUsL.setText("Lista");

        iconeBotaoOpUsL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpUsLLayout = new javax.swing.GroupLayout(botaoOpUsL);
        botaoOpUsL.setLayout(botaoOpUsLLayout);
        botaoOpUsLLayout.setHorizontalGroup(
            botaoOpUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpUsLLayout.createSequentialGroup()
                .addGroup(botaoOpUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botaoOpUsLLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(textoBotaoOpUsL))
                    .addGroup(botaoOpUsLLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(iconeBotaoOpUsL)))
                .addGap(398, 398, 398))
        );
        botaoOpUsLLayout.setVerticalGroup(
            botaoOpUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpUsLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpUsL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpUsL)
                .addGap(16, 16, 16))
        );

        botaoOpUsAu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpUsAu.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpUsAu.setRequestFocusEnabled(false);

        textoBotaoOpUsAu.setText("Adicionar Usuário");

        iconeBotaoOpUsAu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpUsAuLayout = new javax.swing.GroupLayout(botaoOpUsAu);
        botaoOpUsAu.setLayout(botaoOpUsAuLayout);
        botaoOpUsAuLayout.setHorizontalGroup(
            botaoOpUsAuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpUsAuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpUsAu)
                .addGap(61, 61, 61))
            .addGroup(botaoOpUsAuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textoBotaoOpUsAu)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        botaoOpUsAuLayout.setVerticalGroup(
            botaoOpUsAuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpUsAuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpUsAu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpUsAu)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panelOpUsLayout = new javax.swing.GroupLayout(panelOpUs);
        panelOpUs.setLayout(panelOpUsLayout);
        panelOpUsLayout.setHorizontalGroup(
            panelOpUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpUsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpUsLayout.createSequentialGroup()
                        .addComponent(botaoOpUsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botaoOpUsAu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoOpUsEu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelOpUsLayout.setVerticalGroup(
            panelOpUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpUsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoOpUsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOpUsAu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(botaoOpUsEu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelOpPr.setBackground(new java.awt.Color(238, 238, 238));

        botaoOpPrEp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpPrEp.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpPrEp.setRequestFocusEnabled(false);

        textoBotaoOpPrEp.setText("Editar Projeto");

        iconeBotaoOpPrEp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpPrEpLayout = new javax.swing.GroupLayout(botaoOpPrEp);
        botaoOpPrEp.setLayout(botaoOpPrEpLayout);
        botaoOpPrEpLayout.setHorizontalGroup(
            botaoOpPrEpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpPrEpLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(textoBotaoOpPrEp)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpPrEpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpPrEp)
                .addGap(61, 61, 61))
        );
        botaoOpPrEpLayout.setVerticalGroup(
            botaoOpPrEpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpPrEpLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpPrEp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoBotaoOpPrEp)
                .addGap(260, 260, 260))
        );

        botaoOpPrL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpPrL.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpPrL.setRequestFocusEnabled(false);

        textoBotaoOpPrL.setText("Lista");

        iconeBotaoOpPrL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpPrLLayout = new javax.swing.GroupLayout(botaoOpPrL);
        botaoOpPrL.setLayout(botaoOpPrLLayout);
        botaoOpPrLLayout.setHorizontalGroup(
            botaoOpPrLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpPrLLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(textoBotaoOpPrL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpPrLLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpPrL)
                .addGap(61, 61, 61))
        );
        botaoOpPrLLayout.setVerticalGroup(
            botaoOpPrLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpPrLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpPrL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpPrL)
                .addGap(16, 16, 16))
        );

        botaoOpPrAp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpPrAp.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpPrAp.setRequestFocusEnabled(false);

        textoBotaoOpPrAp.setText("Adicionar Projeto");

        iconeBotaoOpPrAp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpPrApLayout = new javax.swing.GroupLayout(botaoOpPrAp);
        botaoOpPrAp.setLayout(botaoOpPrApLayout);
        botaoOpPrApLayout.setHorizontalGroup(
            botaoOpPrApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpPrApLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpPrAp)
                .addGap(61, 61, 61))
            .addGroup(botaoOpPrApLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textoBotaoOpPrAp)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        botaoOpPrApLayout.setVerticalGroup(
            botaoOpPrApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpPrApLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpPrAp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpPrAp)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panelOpPrLayout = new javax.swing.GroupLayout(panelOpPr);
        panelOpPr.setLayout(panelOpPrLayout);
        panelOpPrLayout.setHorizontalGroup(
            panelOpPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpPrLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpPrLayout.createSequentialGroup()
                        .addComponent(botaoOpPrL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botaoOpPrAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoOpPrEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelOpPrLayout.setVerticalGroup(
            panelOpPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpPrLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoOpPrL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOpPrAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(botaoOpPrEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelOpReq.setBackground(new java.awt.Color(238, 238, 238));

        botaoOpReqEr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpReqEr.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpReqEr.setRequestFocusEnabled(false);

        textoBotaoOpReqEr.setText("Editar Requisito");

        iconeBotaoOpReqEr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpReqErLayout = new javax.swing.GroupLayout(botaoOpReqEr);
        botaoOpReqEr.setLayout(botaoOpReqErLayout);
        botaoOpReqErLayout.setHorizontalGroup(
            botaoOpReqErLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpReqErLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(textoBotaoOpReqEr)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpReqErLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpReqEr)
                .addGap(61, 61, 61))
        );
        botaoOpReqErLayout.setVerticalGroup(
            botaoOpReqErLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpReqErLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpReqEr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoBotaoOpReqEr)
                .addGap(260, 260, 260))
        );

        botaoOpReqL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpReqL.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpReqL.setRequestFocusEnabled(false);

        textoBotaoOpReqL.setText("Lista");

        iconeBotaoOpReqL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpReqLLayout = new javax.swing.GroupLayout(botaoOpReqL);
        botaoOpReqL.setLayout(botaoOpReqLLayout);
        botaoOpReqLLayout.setHorizontalGroup(
            botaoOpReqLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpReqLLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(textoBotaoOpReqL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpReqLLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpReqL)
                .addGap(61, 61, 61))
        );
        botaoOpReqLLayout.setVerticalGroup(
            botaoOpReqLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpReqLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpReqL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpReqL)
                .addGap(16, 16, 16))
        );

        botaoOpReqAr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpReqAr.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpReqAr.setRequestFocusEnabled(false);

        textoBotaoOpReqAr.setText("Adicionar Requisito");

        iconeBotaoOpReqAr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpReqArLayout = new javax.swing.GroupLayout(botaoOpReqAr);
        botaoOpReqAr.setLayout(botaoOpReqArLayout);
        botaoOpReqArLayout.setHorizontalGroup(
            botaoOpReqArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpReqArLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpReqAr)
                .addGap(61, 61, 61))
            .addGroup(botaoOpReqArLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(textoBotaoOpReqAr)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        botaoOpReqArLayout.setVerticalGroup(
            botaoOpReqArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpReqArLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpReqAr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpReqAr)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panelOpReqLayout = new javax.swing.GroupLayout(panelOpReq);
        panelOpReq.setLayout(panelOpReqLayout);
        panelOpReqLayout.setHorizontalGroup(
            panelOpReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpReqLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpReqLayout.createSequentialGroup()
                        .addComponent(botaoOpReqL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botaoOpReqAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoOpReqEr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelOpReqLayout.setVerticalGroup(
            panelOpReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpReqLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoOpReqL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOpReqAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(botaoOpReqEr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelOpRel.setBackground(new java.awt.Color(238, 238, 238));

        botaoOpRelPr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpRelPr.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpRelPr.setRequestFocusEnabled(false);

        textoBotaoOpRelPr.setText("Projetos");

        iconeBotaoOpRelPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpRelPrLayout = new javax.swing.GroupLayout(botaoOpRelPr);
        botaoOpRelPr.setLayout(botaoOpRelPrLayout);
        botaoOpRelPrLayout.setHorizontalGroup(
            botaoOpRelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoOpRelPrLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(textoBotaoOpRelPr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpRelPrLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpRelPr)
                .addGap(61, 61, 61))
        );
        botaoOpRelPrLayout.setVerticalGroup(
            botaoOpRelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpRelPrLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpRelPr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpRelPr)
                .addGap(16, 16, 16))
        );

        botaoOpRelReq.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botaoOpRelReq.setPreferredSize(new java.awt.Dimension(187, 127));
        botaoOpRelReq.setRequestFocusEnabled(false);

        textoBotaoOpRelReq.setText("Requisitos");

        iconeBotaoOpRelReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicativo/image/icon-list.png"))); // NOI18N

        javax.swing.GroupLayout botaoOpRelReqLayout = new javax.swing.GroupLayout(botaoOpRelReq);
        botaoOpRelReq.setLayout(botaoOpRelReqLayout);
        botaoOpRelReqLayout.setHorizontalGroup(
            botaoOpRelReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpRelReqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBotaoOpRelReq)
                .addGap(61, 61, 61))
            .addGroup(botaoOpRelReqLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(textoBotaoOpRelReq)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        botaoOpRelReqLayout.setVerticalGroup(
            botaoOpRelReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoOpRelReqLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconeBotaoOpRelReq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textoBotaoOpRelReq)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panelOpRelLayout = new javax.swing.GroupLayout(panelOpRel);
        panelOpRel.setLayout(panelOpRelLayout);
        panelOpRelLayout.setHorizontalGroup(
            panelOpRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpRelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(botaoOpRelPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(botaoOpRelReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panelOpRelLayout.setVerticalGroup(
            panelOpRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpRelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOpRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoOpRelPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOpRelReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        layeredOp.setLayer(panelOpUs, 4);
        layeredOp.setLayer(panelOpPr, 3);
        layeredOp.setLayer(panelOpReq, 2);
        layeredOp.setLayer(panelOpRel, 1);

        javax.swing.GroupLayout layeredOpLayout = new javax.swing.GroupLayout(layeredOp);
        layeredOp.setLayout(layeredOpLayout);
        layeredOpLayout.setHorizontalGroup(
            layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredOpLayout.createSequentialGroup()
                .addComponent(panelOpUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredOpLayout.createSequentialGroup()
                    .addComponent(panelOpReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredOpLayout.createSequentialGroup()
                    .addComponent(panelOpPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredOpLayout.createSequentialGroup()
                    .addComponent(panelOpRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layeredOpLayout.setVerticalGroup(
            layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredOpLayout.createSequentialGroup()
                .addComponent(panelOpUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredOpLayout.createSequentialGroup()
                    .addComponent(panelOpReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredOpLayout.createSequentialGroup()
                    .addComponent(panelOpPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layeredOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredOpLayout.createSequentialGroup()
                    .addComponent(panelOpRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout tabOpLayout = new javax.swing.GroupLayout(tabOp);
        tabOp.setLayout(tabOpLayout);
        tabOpLayout.setHorizontalGroup(
            tabOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabOpLayout.createSequentialGroup()
                .addGroup(tabOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(layeredOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tabOpLayout.setVerticalGroup(
            tabOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabOpLayout.createSequentialGroup()
                .addComponent(titleOp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(layeredOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCo.setPreferredSize(new java.awt.Dimension(942, 834));

        CoUsL.setBorder(null);
        CoUsL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoUsL.setPreferredSize(new java.awt.Dimension(942, 834));
        CoUsL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoUsLMouseClicked(evt);
            }
        });

        panelCoUsL.setBorder(null);
        panelCoUsL.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel12.setText("panelCoUsL");

        javax.swing.GroupLayout panelCoUsLLayout = new javax.swing.GroupLayout(panelCoUsL);
        panelCoUsL.setLayout(panelCoUsLLayout);
        panelCoUsLLayout.setHorizontalGroup(
            panelCoUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsLLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel12)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        panelCoUsLLayout.setVerticalGroup(
            panelCoUsLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsLLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel12)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsL.setViewportView(panelCoUsL);

        javax.swing.GroupLayout CoUsL1Layout = new javax.swing.GroupLayout(CoUsL1);
        CoUsL1.setLayout(CoUsL1Layout);
        CoUsL1Layout.setHorizontalGroup(
            CoUsL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoUsL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoUsL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoUsL1Layout.setVerticalGroup(
            CoUsL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoUsL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoUsL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoRelReq.setBorder(null);
        CoRelReq.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoRelReq.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoRelReq.setBorder(null);
        panelCoRelReq.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel11.setText("panelCoRelReq");

        javax.swing.GroupLayout panelCoRelReqLayout = new javax.swing.GroupLayout(panelCoRelReq);
        panelCoRelReq.setLayout(panelCoRelReqLayout);
        panelCoRelReqLayout.setHorizontalGroup(
            panelCoRelReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelReqLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel11)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        panelCoRelReqLayout.setVerticalGroup(
            panelCoRelReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelReqLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel11)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoRelReq.setViewportView(panelCoRelReq);

        javax.swing.GroupLayout CoRelReq1Layout = new javax.swing.GroupLayout(CoRelReq1);
        CoRelReq1.setLayout(CoRelReq1Layout);
        CoRelReq1Layout.setHorizontalGroup(
            CoRelReq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoRelReq1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoRelReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoRelReq1Layout.setVerticalGroup(
            CoRelReq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoRelReq1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoRelReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoRelPr.setBorder(null);
        CoRelPr.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoRelPr.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoRelPr.setBorder(null);
        panelCoRelPr.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel10.setText("panelCoRelPr");

        javax.swing.GroupLayout panelCoRelPrLayout = new javax.swing.GroupLayout(panelCoRelPr);
        panelCoRelPr.setLayout(panelCoRelPrLayout);
        panelCoRelPrLayout.setHorizontalGroup(
            panelCoRelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelPrLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel10)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        panelCoRelPrLayout.setVerticalGroup(
            panelCoRelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoRelPrLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel10)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoRelPr.setViewportView(panelCoRelPr);

        javax.swing.GroupLayout CoRelPr1Layout = new javax.swing.GroupLayout(CoRelPr1);
        CoRelPr1.setLayout(CoRelPr1Layout);
        CoRelPr1Layout.setHorizontalGroup(
            CoRelPr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoRelPr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoRelPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoRelPr1Layout.setVerticalGroup(
            CoRelPr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoRelPr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoRelPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoReqEr.setBorder(null);
        CoReqEr.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoReqEr.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoReqEr.setBorder(null);
        panelCoReqEr.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel9.setText("panelCoReqEr");

        javax.swing.GroupLayout panelCoReqErLayout = new javax.swing.GroupLayout(panelCoReqEr);
        panelCoReqEr.setLayout(panelCoReqErLayout);
        panelCoReqErLayout.setHorizontalGroup(
            panelCoReqErLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqErLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel9)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        panelCoReqErLayout.setVerticalGroup(
            panelCoReqErLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqErLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel9)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoReqEr.setViewportView(panelCoReqEr);

        javax.swing.GroupLayout CoReqEr1Layout = new javax.swing.GroupLayout(CoReqEr1);
        CoReqEr1.setLayout(CoReqEr1Layout);
        CoReqEr1Layout.setHorizontalGroup(
            CoReqEr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoReqEr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoReqEr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoReqEr1Layout.setVerticalGroup(
            CoReqEr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoReqEr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoReqEr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoReqAr.setBorder(null);
        CoReqAr.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoReqAr.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoReqAr.setBorder(null);
        panelCoReqAr.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel7.setText("panelCoReqAr");

        javax.swing.GroupLayout panelCoReqArLayout = new javax.swing.GroupLayout(panelCoReqAr);
        panelCoReqAr.setLayout(panelCoReqArLayout);
        panelCoReqArLayout.setHorizontalGroup(
            panelCoReqArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqArLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel7)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        panelCoReqArLayout.setVerticalGroup(
            panelCoReqArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqArLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel7)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoReqAr.setViewportView(panelCoReqAr);

        javax.swing.GroupLayout CoReqAr1Layout = new javax.swing.GroupLayout(CoReqAr1);
        CoReqAr1.setLayout(CoReqAr1Layout);
        CoReqAr1Layout.setHorizontalGroup(
            CoReqAr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoReqAr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoReqAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoReqAr1Layout.setVerticalGroup(
            CoReqAr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoReqAr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoReqAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoReqL.setBorder(null);
        CoReqL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoReqL.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoReqL.setBorder(null);
        panelCoReqL.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel8.setText("panelCoReqL");

        javax.swing.GroupLayout panelCoReqLLayout = new javax.swing.GroupLayout(panelCoReqL);
        panelCoReqL.setLayout(panelCoReqLLayout);
        panelCoReqLLayout.setHorizontalGroup(
            panelCoReqLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqLLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel8)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        panelCoReqLLayout.setVerticalGroup(
            panelCoReqLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoReqLLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel8)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoReqL.setViewportView(panelCoReqL);

        javax.swing.GroupLayout CoReqL1Layout = new javax.swing.GroupLayout(CoReqL1);
        CoReqL1.setLayout(CoReqL1Layout);
        CoReqL1Layout.setHorizontalGroup(
            CoReqL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoReqL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoReqL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoReqL1Layout.setVerticalGroup(
            CoReqL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoReqL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoReqL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoPrEp.setBorder(null);
        CoPrEp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoPrEp.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoPrEp.setBorder(null);
        panelCoPrEp.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel6.setText("panelCoPrEp");

        javax.swing.GroupLayout panelCoPrEpLayout = new javax.swing.GroupLayout(panelCoPrEp);
        panelCoPrEp.setLayout(panelCoPrEpLayout);
        panelCoPrEpLayout.setHorizontalGroup(
            panelCoPrEpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrEpLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel6)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        panelCoPrEpLayout.setVerticalGroup(
            panelCoPrEpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrEpLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel6)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoPrEp.setViewportView(panelCoPrEp);

        javax.swing.GroupLayout CoPrEp1Layout = new javax.swing.GroupLayout(CoPrEp1);
        CoPrEp1.setLayout(CoPrEp1Layout);
        CoPrEp1Layout.setHorizontalGroup(
            CoPrEp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoPrEp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoPrEp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoPrEp1Layout.setVerticalGroup(
            CoPrEp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoPrEp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoPrEp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoPrAp.setBorder(null);
        CoPrAp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoPrAp.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoPrAp.setBorder(null);
        panelCoPrAp.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel5.setText("panelCoPrAp");

        javax.swing.GroupLayout panelCoPrApLayout = new javax.swing.GroupLayout(panelCoPrAp);
        panelCoPrAp.setLayout(panelCoPrApLayout);
        panelCoPrApLayout.setHorizontalGroup(
            panelCoPrApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrApLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel5)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        panelCoPrApLayout.setVerticalGroup(
            panelCoPrApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrApLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel5)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoPrAp.setViewportView(panelCoPrAp);

        javax.swing.GroupLayout CoPrAp1Layout = new javax.swing.GroupLayout(CoPrAp1);
        CoPrAp1.setLayout(CoPrAp1Layout);
        CoPrAp1Layout.setHorizontalGroup(
            CoPrAp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoPrAp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoPrAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoPrAp1Layout.setVerticalGroup(
            CoPrAp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoPrAp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoPrAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoUsEu.setBorder(null);
        CoUsEu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoUsEu.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoUsEu.setBorder(null);
        panelCoUsEu.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel3.setText("panelCoUsEu");

        javax.swing.GroupLayout panelCoUsEuLayout = new javax.swing.GroupLayout(panelCoUsEu);
        panelCoUsEu.setLayout(panelCoUsEuLayout);
        panelCoUsEuLayout.setHorizontalGroup(
            panelCoUsEuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsEuLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel3)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        panelCoUsEuLayout.setVerticalGroup(
            panelCoUsEuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsEuLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel3)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsEu.setViewportView(panelCoUsEu);

        javax.swing.GroupLayout CoUsEu1Layout = new javax.swing.GroupLayout(CoUsEu1);
        CoUsEu1.setLayout(CoUsEu1Layout);
        CoUsEu1Layout.setHorizontalGroup(
            CoUsEu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoUsEu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoUsEu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoUsEu1Layout.setVerticalGroup(
            CoUsEu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoUsEu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoUsEu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoPrL.setBorder(null);
        CoPrL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoPrL.setPreferredSize(new java.awt.Dimension(942, 834));

        panelCoPrL.setBorder(null);
        panelCoPrL.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel4.setText("panelCoPrL");

        javax.swing.GroupLayout panelCoPrLLayout = new javax.swing.GroupLayout(panelCoPrL);
        panelCoPrL.setLayout(panelCoPrLLayout);
        panelCoPrLLayout.setHorizontalGroup(
            panelCoPrLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrLLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel4)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        panelCoPrLLayout.setVerticalGroup(
            panelCoPrLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoPrLLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel4)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoPrL.setViewportView(panelCoPrL);

        javax.swing.GroupLayout CoPrL1Layout = new javax.swing.GroupLayout(CoPrL1);
        CoPrL1.setLayout(CoPrL1Layout);
        CoPrL1Layout.setHorizontalGroup(
            CoPrL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoPrL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoPrL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoPrL1Layout.setVerticalGroup(
            CoPrL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoPrL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoPrL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CoUsAu.setBorder(null);
        CoUsAu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CoUsAu.setPreferredSize(new java.awt.Dimension(942, 834));
        CoUsAu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoUsAuMouseClicked(evt);
            }
        });

        panelCoUsAu.setBorder(null);
        panelCoUsAu.setPreferredSize(new java.awt.Dimension(910, 1000));

        jLabel2.setText("panelCoUsAu");

        javax.swing.GroupLayout panelCoUsAuLayout = new javax.swing.GroupLayout(panelCoUsAu);
        panelCoUsAu.setLayout(panelCoUsAuLayout);
        panelCoUsAuLayout.setHorizontalGroup(
            panelCoUsAuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsAuLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel2)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        panelCoUsAuLayout.setVerticalGroup(
            panelCoUsAuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoUsAuLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        CoUsAu.setViewportView(panelCoUsAu);

        javax.swing.GroupLayout CoUsAu1Layout = new javax.swing.GroupLayout(CoUsAu1);
        CoUsAu1.setLayout(CoUsAu1Layout);
        CoUsAu1Layout.setHorizontalGroup(
            CoUsAu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoUsAu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoUsAu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoUsAu1Layout.setVerticalGroup(
            CoUsAu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoUsAu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoUsAu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabCo.setLayer(CoUsL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoRelReq1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoRelPr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoReqEr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoReqAr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoReqL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoPrEp1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoPrAp1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoUsEu1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoPrL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabCo.setLayer(CoUsAu1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tabCoLayout = new javax.swing.GroupLayout(tabCo);
        tabCo.setLayout(tabCoLayout);
        tabCoLayout.setHorizontalGroup(
            tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoUsAu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 48, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoUsEu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CoPrL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrEp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqAr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqEr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelPr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CoUsL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        tabCoLayout.setVerticalGroup(
            tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoUsAu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 48, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoUsEu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CoPrL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoPrEp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqAr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoReqEr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelPr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabCoLayout.createSequentialGroup()
                    .addComponent(CoRelReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(tabCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CoUsL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabOp, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabCo, 966, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tabCo, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
                        .addComponent(tabOp, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CoUsLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoUsLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CoUsLMouseClicked

    private void CoUsAuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoUsAuMouseClicked

    }//GEN-LAST:event_CoUsAuMouseClicked

    private void panelOpUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpUsMouseClicked
        panelOpUs.setVisible(false);
    }//GEN-LAST:event_panelOpUsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CoPrAp;
    private javax.swing.JPanel CoPrAp1;
    private javax.swing.JScrollPane CoPrEp;
    private javax.swing.JPanel CoPrEp1;
    private javax.swing.JScrollPane CoPrL;
    private javax.swing.JPanel CoPrL1;
    private javax.swing.JScrollPane CoRelPr;
    private javax.swing.JPanel CoRelPr1;
    private javax.swing.JScrollPane CoRelReq;
    private javax.swing.JPanel CoRelReq1;
    private javax.swing.JScrollPane CoReqAr;
    private javax.swing.JPanel CoReqAr1;
    private javax.swing.JScrollPane CoReqEr;
    private javax.swing.JPanel CoReqEr1;
    private javax.swing.JScrollPane CoReqL;
    private javax.swing.JPanel CoReqL1;
    private javax.swing.JScrollPane CoUsAu;
    private javax.swing.JPanel CoUsAu1;
    private javax.swing.JScrollPane CoUsEu;
    private javax.swing.JPanel CoUsEu1;
    private javax.swing.JScrollPane CoUsL;
    private javax.swing.JPanel CoUsL1;
    private javax.swing.JPanel botaoOpPrAp;
    private javax.swing.JPanel botaoOpPrEp;
    private javax.swing.JPanel botaoOpPrL;
    private javax.swing.JPanel botaoOpRelPr;
    private javax.swing.JPanel botaoOpRelReq;
    private javax.swing.JPanel botaoOpReqAr;
    private javax.swing.JPanel botaoOpReqEr;
    private javax.swing.JPanel botaoOpReqL;
    private javax.swing.JPanel botaoOpUsAu;
    private javax.swing.JPanel botaoOpUsEu;
    private javax.swing.JPanel botaoOpUsL;
    private javax.swing.JLabel iconeBotaoOpPrAp;
    private javax.swing.JLabel iconeBotaoOpPrEp;
    private javax.swing.JLabel iconeBotaoOpPrL;
    private javax.swing.JLabel iconeBotaoOpRelPr;
    private javax.swing.JLabel iconeBotaoOpRelReq;
    private javax.swing.JLabel iconeBotaoOpReqAr;
    private javax.swing.JLabel iconeBotaoOpReqEr;
    private javax.swing.JLabel iconeBotaoOpReqL;
    private javax.swing.JLabel iconeBotaoOpUsAu;
    private javax.swing.JLabel iconeBotaoOpUsEu;
    private javax.swing.JLabel iconeBotaoOpUsL;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane layeredOp;
    private javax.swing.JPanel panelCoPrAp;
    private javax.swing.JPanel panelCoPrEp;
    private javax.swing.JPanel panelCoPrL;
    private javax.swing.JPanel panelCoRelPr;
    private javax.swing.JPanel panelCoRelReq;
    private javax.swing.JPanel panelCoReqAr;
    private javax.swing.JPanel panelCoReqEr;
    private javax.swing.JPanel panelCoReqL;
    private javax.swing.JPanel panelCoUsAu;
    private javax.swing.JPanel panelCoUsEu;
    private javax.swing.JPanel panelCoUsL;
    private javax.swing.JPanel panelOpPr;
    private javax.swing.JPanel panelOpRel;
    private javax.swing.JPanel panelOpReq;
    private javax.swing.JPanel panelOpUs;
    private javax.swing.JLayeredPane tabCo;
    private javax.swing.JPanel tabOp;
    private javax.swing.JLabel textoBotaoOpPrAp;
    private javax.swing.JLabel textoBotaoOpPrEp;
    private javax.swing.JLabel textoBotaoOpPrL;
    private javax.swing.JLabel textoBotaoOpRelPr;
    private javax.swing.JLabel textoBotaoOpRelReq;
    private javax.swing.JLabel textoBotaoOpReqAr;
    private javax.swing.JLabel textoBotaoOpReqEr;
    private javax.swing.JLabel textoBotaoOpReqL;
    private javax.swing.JLabel textoBotaoOpUsAu;
    private javax.swing.JLabel textoBotaoOpUsEu;
    private javax.swing.JLabel textoBotaoOpUsL;
    private javax.swing.JLabel textoTitleOp;
    private javax.swing.JPanel titleOp;
    // End of variables declaration//GEN-END:variables
}
