/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.requisitos.jframes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JLabel;

public class EditarRequisito extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    public EditarRequisito() {
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        inputNome = new javax.swing.JPanel();
        erroNome = new javax.swing.JLabel();
        tituloNome = new javax.swing.JLabel();
        textFieldDescricao = new javax.swing.JTextField();
        inputDescricao = new javax.swing.JPanel();
        erroDescricao = new javax.swing.JLabel();
        tituloDescricao = new javax.swing.JLabel();
        scrollPaneDescricao = new javax.swing.JScrollPane();
        textAreaDescricao = new javax.swing.JTextArea();
        inputModulo = new javax.swing.JPanel();
        erroModulo = new javax.swing.JLabel();
        tituloModulo = new javax.swing.JLabel();
        textFieldModulo = new javax.swing.JTextField();
        inputFuncionalidades = new javax.swing.JPanel();
        erroFuncionalidades = new javax.swing.JLabel();
        tituloFuncionalidades = new javax.swing.JLabel();
        textFieldFuncionalidades = new javax.swing.JTextField();
        inputDataCriacao = new javax.swing.JPanel();
        erroDataCriacao = new javax.swing.JLabel();
        tituloDataCriacao = new javax.swing.JLabel();
        textFieldDataCriacao = new javax.swing.JTextField();
        inputAutor = new javax.swing.JPanel();
        erroAutor = new javax.swing.JLabel();
        tituloAutor = new javax.swing.JLabel();
        textFieldAutor = new javax.swing.JTextField();
        inputPrioridade = new javax.swing.JPanel();
        erroPrioridade = new javax.swing.JLabel();
        tituloPrioridade = new javax.swing.JLabel();
        textFieldPrioridade = new javax.swing.JTextField();
        inputFase = new javax.swing.JPanel();
        erroFase = new javax.swing.JLabel();
        tituloFase = new javax.swing.JLabel();
        textFieldFase = new javax.swing.JTextField();
        inputEsforcoEstimado = new javax.swing.JPanel();
        erroEsforcoEstimado = new javax.swing.JLabel();
        tituloEsforcoEstimado = new javax.swing.JLabel();
        textFieldEsforcoEstimado = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1295, 697));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setPreferredSize(new java.awt.Dimension(1295, 697));

        panel.setPreferredSize(new java.awt.Dimension(1295, 1303));
        panel.setRequestFocusEnabled(false);

        erroNome.setForeground(new java.awt.Color(242, 13, 13));
        erroNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroNome.setText("erro!");
        erroNome.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloNome.setText("Nome");

        textFieldDescricao.setToolTipText("");
        textFieldDescricao.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputNomeLayout = new javax.swing.GroupLayout(inputNome);
        inputNome.setLayout(inputNomeLayout);
        inputNomeLayout.setHorizontalGroup(
            inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloNome))
                .addContainerGap())
        );
        inputNomeLayout.setVerticalGroup(
            inputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        erroDescricao.setForeground(new java.awt.Color(242, 13, 13));
        erroDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroDescricao.setText("erro!");
        erroDescricao.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloDescricao.setText("Descrição");

        scrollPaneDescricao.setPreferredSize(new java.awt.Dimension(453, 180));

        textAreaDescricao.setColumns(20);
        textAreaDescricao.setRows(10);
        scrollPaneDescricao.setViewportView(textAreaDescricao);

        javax.swing.GroupLayout inputDescricaoLayout = new javax.swing.GroupLayout(inputDescricao);
        inputDescricao.setLayout(inputDescricaoLayout);
        inputDescricaoLayout.setHorizontalGroup(
            inputDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(erroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloDescricao)
                    .addComponent(scrollPaneDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        inputDescricaoLayout.setVerticalGroup(
            inputDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDescricaoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        erroModulo.setForeground(new java.awt.Color(242, 13, 13));
        erroModulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroModulo.setText("erro!");
        erroModulo.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloModulo.setText("Módulo");

        textFieldModulo.setToolTipText("");
        textFieldModulo.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputModuloLayout = new javax.swing.GroupLayout(inputModulo);
        inputModulo.setLayout(inputModuloLayout);
        inputModuloLayout.setHorizontalGroup(
            inputModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldModulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloModulo))
                .addContainerGap())
        );
        inputModuloLayout.setVerticalGroup(
            inputModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputModuloLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        erroFuncionalidades.setForeground(new java.awt.Color(242, 13, 13));
        erroFuncionalidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroFuncionalidades.setText("erro!");
        erroFuncionalidades.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloFuncionalidades.setText("Funcionalidades");

        textFieldFuncionalidades.setToolTipText("");
        textFieldFuncionalidades.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldFuncionalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFuncionalidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputFuncionalidadesLayout = new javax.swing.GroupLayout(inputFuncionalidades);
        inputFuncionalidades.setLayout(inputFuncionalidadesLayout);
        inputFuncionalidadesLayout.setHorizontalGroup(
            inputFuncionalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFuncionalidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputFuncionalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputFuncionalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldFuncionalidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloFuncionalidades))
                .addContainerGap())
        );
        inputFuncionalidadesLayout.setVerticalGroup(
            inputFuncionalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFuncionalidadesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloFuncionalidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        erroDataCriacao.setForeground(new java.awt.Color(242, 13, 13));
        erroDataCriacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroDataCriacao.setText("erro!");
        erroDataCriacao.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloDataCriacao.setText("Data de Criação (dd/mm/aaaa)");

        textFieldDataCriacao.setToolTipText("");
        textFieldDataCriacao.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldDataCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDataCriacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputDataCriacaoLayout = new javax.swing.GroupLayout(inputDataCriacao);
        inputDataCriacao.setLayout(inputDataCriacaoLayout);
        inputDataCriacaoLayout.setHorizontalGroup(
            inputDataCriacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDataCriacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputDataCriacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputDataCriacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldDataCriacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloDataCriacao))
                .addContainerGap())
        );
        inputDataCriacaoLayout.setVerticalGroup(
            inputDataCriacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDataCriacaoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloDataCriacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        erroAutor.setForeground(new java.awt.Color(242, 13, 13));
        erroAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroAutor.setText("erro!");
        erroAutor.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloAutor.setText("Autor");

        textFieldAutor.setToolTipText("");
        textFieldAutor.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputAutorLayout = new javax.swing.GroupLayout(inputAutor);
        inputAutor.setLayout(inputAutorLayout);
        inputAutorLayout.setHorizontalGroup(
            inputAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloAutor))
                .addGap(24, 24, 24))
        );
        inputAutorLayout.setVerticalGroup(
            inputAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputAutorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        erroPrioridade.setForeground(new java.awt.Color(242, 13, 13));
        erroPrioridade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroPrioridade.setText("erro!");
        erroPrioridade.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloPrioridade.setText("Prioridade");

        textFieldPrioridade.setToolTipText("");
        textFieldPrioridade.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldPrioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrioridadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPrioridadeLayout = new javax.swing.GroupLayout(inputPrioridade);
        inputPrioridade.setLayout(inputPrioridadeLayout);
        inputPrioridadeLayout.setHorizontalGroup(
            inputPrioridadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPrioridadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPrioridadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPrioridadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldPrioridade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloPrioridade))
                .addContainerGap())
        );
        inputPrioridadeLayout.setVerticalGroup(
            inputPrioridadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPrioridadeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloPrioridade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        erroFase.setForeground(new java.awt.Color(242, 13, 13));
        erroFase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroFase.setText("erro!");
        erroFase.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloFase.setText("Fase");

        textFieldFase.setToolTipText("");
        textFieldFase.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputFaseLayout = new javax.swing.GroupLayout(inputFase);
        inputFase.setLayout(inputFaseLayout);
        inputFaseLayout.setHorizontalGroup(
            inputFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroFase, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldFase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloFase))
                .addContainerGap())
        );
        inputFaseLayout.setVerticalGroup(
            inputFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFaseLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloFase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldFase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        erroEsforcoEstimado.setForeground(new java.awt.Color(242, 13, 13));
        erroEsforcoEstimado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroEsforcoEstimado.setText("erro!");
        erroEsforcoEstimado.setPreferredSize(new java.awt.Dimension(453, 18));

        tituloEsforcoEstimado.setText("Esforço estimado (horas)");

        textFieldEsforcoEstimado.setToolTipText("");
        textFieldEsforcoEstimado.setPreferredSize(new java.awt.Dimension(453, 40));
        textFieldEsforcoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEsforcoEstimadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputEsforcoEstimadoLayout = new javax.swing.GroupLayout(inputEsforcoEstimado);
        inputEsforcoEstimado.setLayout(inputEsforcoEstimadoLayout);
        inputEsforcoEstimadoLayout.setHorizontalGroup(
            inputEsforcoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputEsforcoEstimadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputEsforcoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputEsforcoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erroEsforcoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldEsforcoEstimado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloEsforcoEstimado))
                .addContainerGap())
        );
        inputEsforcoEstimadoLayout.setVerticalGroup(
            inputEsforcoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputEsforcoEstimadoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tituloEsforcoEstimado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldEsforcoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroEsforcoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botaoSalvar.setText("Salvar");
        botaoSalvar.setMaximumSize(new java.awt.Dimension(127, 40));
        botaoSalvar.setMinimumSize(new java.awt.Dimension(127, 40));
        botaoSalvar.setPreferredSize(new java.awt.Dimension(127, 40));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputEsforcoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inputModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inputFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inputAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inputPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(inputEsforcoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inputFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inputDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDescricaoActionPerformed

    private void textFieldModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldModuloActionPerformed

    private void textFieldFuncionalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFuncionalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFuncionalidadesActionPerformed

    private void textFieldDataCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDataCriacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDataCriacaoActionPerformed

    private void textFieldAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAutorActionPerformed

    private void textFieldPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPrioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrioridadeActionPerformed

    private void textFieldFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFaseActionPerformed

    private void textFieldEsforcoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEsforcoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEsforcoEstimadoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarRequisito().setVisible(true);
            }
        });
    }
    
    private void inicializarComponentes () {
        
        // mensagens de erro
        mensagensDeErro = new ArrayList<>();
                
        mensagensDeErro.addAll(
                
                Arrays.asList(
                        erroNome,
                        erroModulo,
                        erroFuncionalidades,
                        erroDataCriacao,
                        erroAutor,
                        erroPrioridade,
                        erroEsforcoEstimado,
                        erroFase,
                        erroDescricao
                )
                
        );
        
        mensagensDeErro.forEach( 
                erro -> {
                    erro.setVisible(false);
                }
        );
        
    }

    private List<JLabel> mensagensDeErro;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel erroAutor;
    private javax.swing.JLabel erroDataCriacao;
    private javax.swing.JLabel erroDescricao;
    private javax.swing.JLabel erroEsforcoEstimado;
    private javax.swing.JLabel erroFase;
    private javax.swing.JLabel erroFuncionalidades;
    private javax.swing.JLabel erroModulo;
    private javax.swing.JLabel erroNome;
    private javax.swing.JLabel erroPrioridade;
    private javax.swing.JPanel inputAutor;
    private javax.swing.JPanel inputDataCriacao;
    private javax.swing.JPanel inputDescricao;
    private javax.swing.JPanel inputEsforcoEstimado;
    private javax.swing.JPanel inputFase;
    private javax.swing.JPanel inputFuncionalidades;
    private javax.swing.JPanel inputModulo;
    private javax.swing.JPanel inputNome;
    private javax.swing.JPanel inputPrioridade;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPaneDescricao;
    private javax.swing.JTextArea textAreaDescricao;
    private javax.swing.JTextField textFieldAutor;
    private javax.swing.JTextField textFieldDataCriacao;
    private javax.swing.JTextField textFieldDescricao;
    private javax.swing.JTextField textFieldEsforcoEstimado;
    private javax.swing.JTextField textFieldFase;
    private javax.swing.JTextField textFieldFuncionalidades;
    private javax.swing.JTextField textFieldModulo;
    private javax.swing.JTextField textFieldPrioridade;
    private javax.swing.JLabel tituloAutor;
    private javax.swing.JLabel tituloDataCriacao;
    private javax.swing.JLabel tituloDescricao;
    private javax.swing.JLabel tituloEsforcoEstimado;
    private javax.swing.JLabel tituloFase;
    private javax.swing.JLabel tituloFuncionalidades;
    private javax.swing.JLabel tituloModulo;
    private javax.swing.JLabel tituloNome;
    private javax.swing.JLabel tituloPrioridade;
    // End of variables declaration//GEN-END:variables
}
